<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Display Doc page, 120x240 ads, Inline with content */
google_ad_slot = "6430985967";
google_ad_width = 120;
google_ad_height = 240;
if (width > 500) {
  /* Display Doc page, 300x250 ads, Right hand side near top */
  google_ad_slot = "4424598596";
  google_ad_width = 300;
  google_ad_height = 250;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
