<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Doc page, 320x50 ads, Inline with content */
google_ad_slot = "6291385166";
google_ad_width = 320;
google_ad_height = 50;
if (width > 750) {
  /* Doc page, 728x90 ads, Under title */
  google_ad_slot = "1719180562";
  google_ad_width = 728;
  google_ad_height = 90;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
