<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Download page, 160x600 ads, Right hand side near top */
google_ad_slot = "4759062104";
google_ad_width = 160;
google_ad_height = 600;
if (width > 1000) {
  /* Download page, 300x600 Ads, Right hand side near top */
  google_ad_slot = "9053253568";
  google_ad_width = 300;
  google_ad_height = 600;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
