<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Features page, 120x240 ads, Inline with content */
google_ad_slot = "9384452366";
google_ad_width = 120;
google_ad_height = 240;
if (width > 500) {
  /* Features page, 336x280 ads, Right hand side near top */
  google_ad_slot = "0875186746";
  google_ad_width = 336;
  google_ad_height = 280;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
