<!--  Edited by Curtis Gedak Oct 13, 2010 to pass html validation
      NOTE: Moved google branding import to function.php

<style type="text/css">
@import url(http://www.google.com/cse/api/branding.css);
</style>

-->
<div class="cse-branding-bottom" style="background-color:#FFFFFF;color:#000000">
  <div class="cse-branding-form">
    <form action="http://gparted.org/search-results.php" id="cse-search-box">
      <div>
        <input type="hidden" name="cx" value="partner-pub-6388742802791691:73srgg-c1os" />
        <input type="hidden" name="cof" value="FORID:10" />
        <input type="hidden" name="ie" value="ISO-8859-1" />
        <input type="text" name="q" size="16" />
        <input type="submit" name="sa" value="Search" />
      </div>
    </form>
  </div>
  <div class="cse-branding-logo">
    <img src="http://www.google.com/images/poweredby_transparent/poweredby_FFFFFF.gif" alt="Google" />
  </div>
  <div class="cse-branding-text">
    Custom Search
  </div>
</div>
