<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Home page, 120x240 ads, Inline with content */
google_ad_slot = "3955197568";
google_ad_width = 120;
google_ad_height = 240;
if (width > 500) {
  /* Home page, 336x280 ads, Right hand side near features */
  google_ad_slot = "7046659124";
  google_ad_width = 336;
  google_ad_height = 280;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
