<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Live CD page, 120x240 ads, Inline with content */
google_ad_slot = "2477060368";
google_ad_width = 120;
google_ad_height = 240;
if (width > 500) {
  /* Live CD page, 160x600 ads, Right hand side near top */
  google_ad_slot = "1531402778";
  google_ad_width = 160;
  google_ad_height = 600;
}
if (width > 800) {
  /* Live CD page, 336x280 ads, Right hand side near top */
  google_ad_slot = "8523593961";
  google_ad_width = 336;
  google_ad_height = 280;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
