<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Site pages, 320x50 ads, Below page content */
google_ad_slot = "2338863563";
google_ad_width = 320;
google_ad_height = 50;
if (width > 500) {
  /* Site pages, 468x60 ads, Below page content */
  google_ad_slot = "3675995969";
  google_ad_width = 468;
  google_ad_height = 60;
}
if (width > 750) {
  /* Site pages, 728x90 ads, Below page content */
  google_ad_slot = "5925625433";
  google_ad_width = 728;
  google_ad_height = 90;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
