<script type="text/javascript"><!--
google_ad_client = "ca-pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Site pages, 320x50 ads, Above page content */
google_ad_slot = "6908663966";
google_ad_width = 320;
google_ad_height = 50;
if (width > 750) {
  /* Site pages, 728x90 ads, Above page content */
  google_ad_slot = "0776862578";
  google_ad_width = 728;
  google_ad_height = 90;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
