<script type="text/javascript"><!--
google_ad_client = "pub-6388742802791691";
width = document.documentElement.clientWidth;
/* Screen Shot page, 320x50 ads, Inline with content */
google_ad_slot = "3337918761";
google_ad_width = 320;
google_ad_height = 50;
if (width > 500) {
  /* Screen Shot page, 468x60 ads, Under title */
  google_ad_slot = "3034618845";
  google_ad_width = 468;
  google_ad_height = 60;
}
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
